HR_Management.WebMvc/Controllers/LeaveAllocationController.cs
using HR_Management.WebMvc.Cantracts;
using HR_Management.WebMvc.Models.LeaveAllocation;
using HR_Management.WebMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.WebMvc.Controllers
{
    [Authorize]
    public class LeaveAllocationController : Controller
    {

        private readonly ILeaveAllocationService _leaveAllocationService;
        private readonly ILeaveTypeService _leaveTypeService;

        public LeaveAllocationController(ILeaveAllocationService leaveAllocationService, ILeaveTypeService leaveTypeService)
        {
            _leaveAllocationService = leaveAllocationService;
            _leaveTypeService = leaveTypeService;
        }

        // GET: LeaveAllocationController
        public async Task<ActionResult> Index()
        {
            var leaveAllocations = await _leaveAllocationService.GetLeavaAllocationList();
            return View(leaveAllocations);
        }

        // GET: LeaveAllocationController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaveAllocation = await _leaveAllocationService.GetLeaveAllocationBy(id);
            return View(leaveAllocation);
        }

        // GET: LeaveAllocationController/Create
        public async Task<ActionResult> Create()
        {
            return View(new CreateLeaveAllocationViewModel
            {
                LeaveTypes = await _leaveTypeService.GetLeaveTypesList()
            });
        }

        // POST: LeaveAllocationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveAllocationViewModel createLeaveAllocation)
        {
            try
            {
                var result = await _leaveAllocationService.CreateLeaveAllocation(createLeaveAllocation);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            createLeaveAllocation.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(createLeaveAllocation);
        }

        // GET: LeaveAllocationController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _leaveAllocationService.GetLeaveAllocationForUpdate(id);
            model.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(model);
        }

        // POST: LeaveAllocationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateLeaveAllocationViewModel updateLeaveAllocation)
        {
            try
            {
                updateLeaveAllocation.Id = id;
                var result = await _leaveAllocationService.UpdateLeaveAllocation(updateLeaveAllocation);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            updateLeaveAllocation.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(updateLeaveAllocation);
        }

        // GET: LeaveAllocationController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var result = await _leaveAllocationService.DeleteLeaveAllocation(id);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return BadRequest();
        }
    }
}

HR_Management.WebMvc/Controllers/LeaveRequestController.cs
using HR_Management.WebMvc.Cantracts;
using HR_Management.WebMvc.Models.LeaveRequest;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace HR_Management.WebMvc.Controllers
{
    [Authorize]
    public class LeaveRequestController : Controller
    {

        private readonly ILeaveRequestService _leaveRequestService;
        private readonly ILeaveTypeService _leaveTypeService;
        public LeaveRequestController(ILeaveRequestService leaveRequestService, ILeaveTypeService leaveTypeService)
        {
            _leaveRequestService = leaveRequestService;
            _leaveTypeService = leaveTypeService;
        }

        // GET: LeaveRequestController
        public async Task<ActionResult> Index()
        {
            var leaveRequests = await _leaveRequestService.GetLeaveRequestList();
            return View(leaveRequests);
        }

        // GET: LeaveRequestController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaveRequest = await _leaveRequestService.GetLeaveRequestBy(id);
            return View(leaveRequest);
        }

        // GET: LeaveRequestController/Create
        public async Task<ActionResult> Create()
        {
            return View(new CreateLeaveRequestViewModel()
            {
                LeaveTypes = await _leaveTypeService.GetLeaveTypesList()
            });
        }

        // POST: LeaveRequestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveRequestViewModel createLeaveRequest)
        {
            try
            {
                var result = await _leaveRequestService.CreateLeaveRequest(createLeaveRequest);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            createLeaveRequest.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(createLeaveRequest);
        }

        // GET: LeaveRequestController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _leaveRequestService.GetLeaveRequestForUpdate(id);
            model.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(model);
        }

        // POST: LeaveRequestController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateLeaveRequestViewModel updateLeaveRequest)
        {
            try
            {
                updateLeaveRequest.Id = id;
                var result = await _leaveRequestService.UpdateLeaveRequest(updateLeaveRequest);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            updateLeaveRequest.LeaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View();
        }

        // GET: LeaveRequestController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var result = await _leaveRequestService.DeleteLeaveRequest(id);

                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return BadRequest();
        }
    }
}

HR_Management.WebMvc/Controllers/LeaveTypeController.cs
using HR_Management.WebMvc.Cantracts;
using HR_Management.WebMvc.Models.LeaveType;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HR_Management.WebMvc.Controllers
{
    [Authorize]
    public class LeaveTypeController : Controller
    {

        private readonly ILeaveTypeService _leaveTypeService;
        public LeaveTypeController(ILeaveTypeService leaveTypeService)
        {
            _leaveTypeService = leaveTypeService;
        }

        // GET: LeaveTypeController
        public async Task<ActionResult> Index()
        {
            var leaveTypes = await _leaveTypeService.GetLeaveTypesList();
            return View(leaveTypes);
        }

        // GET: LeaveTypeController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var leaveType = await _leaveTypeService.GetLeaveTypesBy(id);
            return View(leaveType);
        }

        // GET: LeaveTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveTypeViewModel createLeaveType)
        {
            try
            {
                var result = await _leaveTypeService.CreateLeaveType(createLeaveType);

                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(createLeaveType);
        }

        // GET: LeaveTypeController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _leaveTypeService.GetLeaveTypeForUpdate(id);

            return View(model);
        }

        // POST: LeaveTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateLeaveTypeViewModel updateLeaveType)
        {
            try
            {
                updateLeaveType.Id = id;
                var result = await _leaveTypeService.UpdateLeaveType(updateLeaveType);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.ValidationErrors);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(updateLeaveType);
        }

        // GET: LeaveTypeController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var result = await _leaveTypeService.DeleteLeaveType(id);

                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return BadRequest();
        }
    }
}

HR_Management.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR_Management.WebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HR_Management.WebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR Management - @User.Identity.Name</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR Management</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <partial name="_LoggedInPartial" />

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HR_Management.WebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HR_Management.WebMvc/Views/Shared/_LoggedInPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="LeaveType" asp-action="Index">LeaveTypes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="LeaveAllocation" asp-action="Index">LeaveAllocations</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="LeaveRequest" asp-action="Index">LeaveRequests</a>
    </li>
    <li class="nav-item">
        <form method="post" asp-area="" asp-controller="Authentication" asp-action="Logout">
            <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
    </li>

}